name: shiyi_player
description: "十一 · 接着奏乐 —— 本地离线音乐播放器（Android）"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
